hypercerts-org/hypercerts-app

app/hypercerts/new/form-steps.tsx, components/allowlist/create-allowlist-dialog.tsx, configs/constants.ts, hypercerts/getAllHypercerts.ts
Updates allowlist upload flow to check on correct field to varify validation 
Closes #200
=> fix(allowlist): restores allowlist upload and minting functionality

app/profile/[address]/collections-tab-content.tsx, app/profile/[address]/sections.tsx, components/marketplace/hypercert-listings-list.tsx, components/marketplace/user-listings-list.tsx
=> fix: no listings and no collections messages

components/marketplace/list-dialog.tsx
=> fix: automatically select first fraction owned by user and prefill form values

hypercerts/getEvaluationStatus.ts
=> fix(copy): updates evaluation status tags

components/global/navbar.tsx, configs/site.ts
* Moves `Create hypercert` to top level in nav bar
* Conditionally renders `my hypercerts` link in nav bar when logged in
Closes #191
=> fix: remove create dropdown and add my hypercerts

app/evaluators/page.tsx, components/evaluators/evaluators-list-row.tsx, components/evaluators/evaluators-list.tsx, components/global/navbar.tsx, configs/ui.ts
* Sets evaluator count on evaluators page to 20
* Set max width of evaluator overview
* Fixes create-hypercert link in nav bar
Closes #194
=> fix(ui): max page width and increase row count

components/chain-display.tsx, components/global/navbar.tsx
* Updates 'Create hypercert' to 'Create'
* Updates nav bar link styling to apply correct styling based on path
* Fixes bug in connected chain icon that would break on unsupported chains
=> fix(ui): navbar styling and connected chain icon

app/hypercerts/new/form-steps.tsx, app/hypercerts/new/page.tsx, package.json, pnpm-lock.yaml
* use local storage to store defaul values in cache
* on update write form state to cache
* adds reset button to clear form state, cache and return to first step
* on page refresh load the form state from local storage
works on #152
=> feat(cache): use local storage to cache and fetch form state

package.json, pnpm-lock.yaml
Updates marketplace SDK to use version with correct address configuration
Closes #202
=> chore(bump): sdks

app/profile/[address]/hypercerts-tab-content.tsx, components/explore/explore-list.tsx
Constrained columns to a max width, converted from px to rem.
=> fix: explosion of the width of cards with only 1 - 3 cards on page

configs/hypercerts.ts
=> fix: get correct api url

app/hypercerts/new/form-steps.tsx
* Allows for capital letters in tags
* Allows for capital letters and spaced in contributors
https://testnet.hypercerts.org/hypercerts/11155111-0xa16DFb32Eb140a6f3F2AC68f41dAd8c7e83C4941-229690597671633462837777860016443542732800
=> fix: tag and contributor input parsing

app/hypercerts/[hypercertId]/page.tsx, components/hypercert/burn-button.tsx, components/hypercert/burn-drawer.tsx, components/hypercert/transfer-button.tsx, components/hypercert/transfer-drawer.tsx, package.json, pnpm-lock.yaml
* Add Transfer and Burn button to hypercert view page
* Create drawers for transfer and burn interaction
=> Transfer and burn buttons

app/hypercerts/[hypercertId]/page.tsx, components/hypercert/mutation-buttons.tsx, components/hypercert/split-drawer.tsx
* Restore rendering of div containing name and mutation buttons to full width
* Faster loading of page using dynamic components
* Removes icons from transfer, split and burn menu options
* Removes 'NEW' from new fractions in split flow
=> fix(hypercert): improve page rendering and mutation button icons

components/allowlist/create-allowlist-dialog.tsx, components/formatted-units.tsx, components/hypercert/evaluate-drawer.tsx, components/hypercert/hypercert-minting-form/form-steps.tsx
* Support two decimal input
* Render suggested allowlist records with decimals if applicable
=> Support two decimals in allowlist create form

app/hypercerts/[hypercertId]/page.tsx, components/currency-buttons.tsx, components/explore/explore-filters-layout.tsx, components/marketplace/hypercert-listings-list.tsx, pnpm-lock.yaml
* removes unused `value` prop in `CurrencyButtons` component
* read current currency state from search parameters
=> Represent state change in buttons for usd and token

components/marketplace/list-dialog-settings-form.tsx, marketplace/hooks.tsx
* fix: invalidate orders when listing hypercert for sale
* fix: allow for setting units min per order to 0 without crashing
=> Bugfix/hyperforest support (#315)

components/marketplace/buy-button.tsx, components/marketplace/hypercert-listings.tsx
* Adds error logged when div with ID `marketplace-listings` is not found
* Adds `marketplace-listings` id to `MarketplaceListings` component top div
=> Fix buy button routing

components/evaluations/evaluations-list.tsx
Rearranges header based on review feedback
=> Rearrange evaluation list item headers

app/layout.tsx, lib/VercelAnalytics.tsx, next.config.mjs
Masks vercel behind our own api endpoint so it won't get blocked by ublock and other domain blockers.
=> feat(track): add analytics masking

components/read-more.tsx
Applies the rehype sanitation plugin to the HypercertDetails ReadMore component.
=> Input sanitation details view

configs/eas.ts
=> feat(eas): add Base Sepolia network configuration on eas config

hypercerts/getAllHypercerts.ts
adding one hypercert ID to the list of filtered out hypercerts
=> filtering out one more hypercert

app/hypercerts/[hypercertId]/page.tsx
wrapped accordionItem with id so that "buy" Button can navigate properly
Closes #339
=> fix: buy button navigation

components/global/extra-content.tsx, components/marketplace/hypercert-listings-table.tsx, hooks/use-hypercert-exchange-client.ts, lib/utils.ts, marketplace/BuyFractionalStrategy.ts, marketplace/EOABuyFractionalStrategy.tsx, marketplace/SafeBuyFractionalStrategy.tsx, marketplace/hooks.tsx, marketplace/types.ts, marketplace/useBuyFractionalStrategy.ts, package.json, pnpm-lock.yaml
Dependant on https://github.com/hypercerts-org/marketplace-sdk
- Refactors the Buy order execution flow into separate strategies
- Uses the updated marketplace SDK to submit txs to Safe accounts
- Updates the modal stepper to explicity relay relevant information for the Safe flow
=> Safe integration marketplace buy

app/hypercerts/new-transferable/page.tsx, app/hypercerts/new/page.tsx, components/hypercert/hypercert-minting-form/index.tsx, components/hypercert/hypercert-window.tsx, components/marketplace/list-dialog.tsx, hooks/use-hypercert-client.ts, hypercerts/getAllHypercerts.ts, lib/formatPercentage.ts, test/lib/formatPercentage.test.ts
Update getAllHypercerts to correctly determine the number of filtered out hypercerts and adjust the total count accordingly
=> Push to PRD

components/hypercert/hypercert-details.tsx
Change layout place of time and work scopes on the hypercert detail page
=> feat: reorganize time or work and scopes

components/collections/collection-form.tsx
For the time being we don't want to support creating a collection from a Safe. Display a warning banner when the user has a Safe selected and disable the submit button.
=> Show warning banner when Safe selected

app/hypercerts/[hypercertId]/loading.tsx
Create a new file, `loading.tsx` which is rendered by NextJS by default while the hypercert page is loading.
Better user experience due because seeing a loading state makes it feel fast when you click any hypercert.
=> feat: create a loading state while the hypercert data loads
