hypercerts-org/hypercerts-app

- allowlists/getAllowListRecordsForAddressByClaimed.tsx
- app/profile/[address]/hypercerts-tab-content.tsx
- app/profile/[address]/page.tsx
- components/profile/unclaimed-hypercert-claim-button.tsx
- components/profile/unclaimed-hypercert-list-item.tsx
- components/profile/unclaimed-hypercerts-list.tsx
- hypercerts/getHypercertsByCreator.ts
- hypercerts/getHypercertsByOwner.ts
* Updates `getAllowListRecordsForAddressByClaimed` to accept `claimed` param
* Updated Profile `page.tsx` to handle `null` response in data
* Cleaned up redundant logs
> fix(gql): handle null response fetching allowlist records better

- app/explore/page.tsx
- components/explore/explore-chain-filter-select.tsx
- components/explore/explore-evaluations-filter-select.tsx
- components/explore/explore-filters-layout.tsx
- components/explore/explore-list.tsx
- components/explore/explore-order-by-select.tsx
- components/global/mobile-nav.tsx
- components/global/navbar.tsx
- Refactored explore page filters layout for improved responsiveness
- Updated mobile navigation links
- Added tooltip for "My hypercerts" link when user is not signed in
- Limited hypercert window expansion size in explore list
- [163a7a6](https://github.com/hypercerts-org/hypercerts-app/commit/163a7a63a3c016b61ff944c3e2b83f01de7809ea): Add tooltip for "My hypercerts" link when user is not signed in
- [748247e](https://github.com/hypercerts-org/hypercerts-app/commit/748247ecf238e2e40f2ef6f107278db9856b7b89): Update responsive styles for filters on explore page
- [08f85fe](https://github.com/hypercerts-org/hypercerts-app/commit/08f85fec361cb31c86d4e2a7d17b5d1129c140c1): Update mobile nav links
- [393f608](https://github.com/hypercerts-org/hypercerts-app/commit/393f608840070ba61b6ea1ce2237c …
> Beyondr-20240928

- components/evaluation-list-item/comments.tsx
- components/hypercert/evaluations-list.tsx
* Refactors evaluations list to represent evaluations using cards
* Truncate the comment at 200 chars and allow for expanding into a scrollable interface
> feat: evaluations cards in hypercert view

- components/marketplace/buy-fractional-order-form.tsx
- configs/hypercerts.ts
- marketplace/hooks.tsx
- marketplace/utils.ts
- test/marketplace/utils.test.ts
* fix: prevent rounding errors in unit calculations by using DEFAULT_NUM_FRACTIONS precision
* fix: disable form when calculated number of units reaches 0, show price 0
* fix: calculate total price using units not percentage in fractional order form
* fix: remove magic number for number of decimals in hypercert units
* fix: remove redundant utility function getTotalPriceFromPercentage
> Fix/fractional order form rounding errors (#317)

- hypercerts/getAllHypercerts.ts
This PR implement a ducttape method for filtering out burned hypercerts on the frontend. Because technically the explore page loads all claims, and not all fractions, burned claims are still displayed. Untill we have a robust mechanism implemented in our backend, we maintain this filter while queried hypercerts are parsed.
* Adds a filter set to `getAllHypercerts`
* Updates returned count based on filtered results
> Filter burned claim IDs

- hooks/useSafeAccounts.ts
- lib/evmClient.ts
- safe/SafeApiKitStrategy.ts
- settings/SafeSettingsSigningStrategy.ts
- test/lib/evmClient.test.ts
Without this patch the instantiation of the Safe API Kit object fails
due to the Filecoin networks requiring a specific Transaction Service
URL. Usually these are determined by the SDK by providing it with just
the chain id. Since the TX Service on Filecoin and Filecoin Calibration
are hosted by a third party the SDK can't infer them.
This adds a strategy that constructs the Safe API Kit instance
differently based on the current chain id.
> Construct SafeAPIKit instance differently for Filecoin Mainnet and Filecoin Calibration

- commitlintrc.ts
- components/connect-dialog.tsx
- components/disconnect-dialog.tsx
- components/global/step-process-dialog.tsx
- components/marketplace/buy-order-dialog.tsx
- components/marketplace/list-dialog.tsx
- hooks/use-ethers-provider.ts
- lib/decodeContractError.ts
- marketplace/hooks.tsx
- Makes sure the hypercerts exchange client is instantiated using the correct RPC url from our shiny new EvmClientFactory
- Fixes annoying commitlint rule
- Fixes many react console errors and warnings, which makes for a much better dev experience
- Enhances `decodeContractError` to more often get a human-readable error message when a contract interaction fails
> WIP: Feat/ethers provider rpc update

- components/global/footer.tsx
- configs/site.ts
replaced discord link in footer.tsx and site.ts with link that won't expire
> fix: broken discord link in footer.tsx and site.ts

- package.json
- pnpm-lock.yaml
Gets rid of the pesky `multiple GoTrueClient` errors.
> chore: bump-marketplace-sdk

- components/hypercert/hypercert-details.tsx
- components/marketplace/buy-button.tsx
Closes #439 
Disable buy button when no marketplace orders exist for the hypercert
- fetch active order inside the `hypercert/hypercert-details`
- pass "isListed" props to `buy-button` component
- disabled `buy-button` when isListed is false
https://www.loom.com/share/48d136940daa40b1b1a348ae54efa5c0?sid=c1faa939-62a5-4ffa-8296-d3590db22eba
> feat: add buy button listing status

- components/global/step-process-dialog.tsx
Closes: #390 
This change is intended to allow the user to leave the step dialog during the tx execution(any kind of action) and to check  the status on toast. toast is displayed when user closes the dialog
https://www.loom.com/share/4d886d05a7fe494da0e71d58e7e70e73?sid=06ed78c9-c184-4535-a873-98820fb815dd
> feat(dialog): add toast for step process dialog

- collections/hooks.ts
- components/collections/collection-form.tsx
- components/hypercert/hypercert-card.tsx
- components/hypercert/hypercert-minting-form/form-steps.tsx
- components/hypercert/hypercert-minting-form/index.tsx
- components/image-uploader.tsx
- components/settings/settings-form.tsx
Closes #388 
- introduces image uploader component(as a button) that allows user to upload image file
- apply image uploader to minting, collection and setting form
- add process for storing an image on IPFS first for collection and setting form
> feat: upload image

- hypercerts/getAllHypercerts.ts
Update getAllHypercerts to correctly determine the number of filtered out hypercerts and adjust the total count accordingly
> fix: correct hypercerts count calculation

- hooks/use-hypercert-client.ts
injecting our own public client into the hypercert client will ensure we use our own rpc url's within the hypercert exchange client. this prevents the viem defaults being used which error out regularly
> chore: inject public client into hypercert client

- .github/workflows/build-and-test.yml
- .github/workflows/create-release-pr.yml
- lib/evmClient.ts
- package.json
- test/lib/evmClient.test.ts
We are going to rename two of our branches. `main` -> `release` and `dev` -> `main`. More details in issue #473.
I implemented two new actions:
1. Create a new release-to-production PR (targets `release`) when a PR is merged into `main`
2. Build, test and lint the frontend code when a PR is opened against `dev`, `main` or `release`.
> New GitHub actions

- lib/account-store.ts
Without this patch, when having selected a Safe account and refreshing the page, the connected EOA is selected again. Users will have to re-select the Safe, if they want to continue acting on behalf of the Safe.
This patch add persistence to the user account selection using zustand.
> Keep selected Safe after refresh

- app/profile/[address]/page.tsx
- components/profile/contract-accounts-banner.tsx
- hooks/useIsContract.ts
When viewing the profile of a smart contract address, there is a non-zero chance that the ownership across different networks varies. This could be exploitet, so it's best to prompt the users to do their own research.
> Show warning banner when viewing smart contract account

- components/global/extra-content.tsx
- hypercerts/EOAMintHypercertStrategy.ts
- hypercerts/MintHypercertStrategy.ts
- hypercerts/SafeMintHypercertStrategy.tsx
- hypercerts/hooks/useMintHypercert.ts
- hypercerts/hooks/useMintHypercertStrategy.ts
- marketplace/SafeBuyFractionalStrategy.tsx
- marketplace/useBuyFractionalStrategy.ts
- package.json
- pnpm-lock.yaml
This PR adds support for the user to mint a Hypercert using their Safe.
By passing the Safe address into the SDK function (via the `overrides` object) the Safe flow is invoked. The minting dialog now shows only the steps to propose a Safe transaction and invokes `mintHypercert()` on the Hypercerts SDK.
You can see a Safe transaction that was created with the new Hypercerts SDK version and the changes from this PR [here](https://app.safe.global/transactions/tx?id=multisig_0x6C622Ca31a755b4A543f1FE1dB26A666A468Fda8_0x4c7372ba41b279452ee012a0a619de00873ec4e556b0e8feac38bf6fb4c32236&safe=sep:0x6C622Ca31a755b4A543f1FE1dB26A666A468Fda8).
> Safe support for minting a Hypercert

- hooks/use-hypercert-client.ts
Added error handling for the public client creation process to prevent crashes when the wallet client is not properly initialized.
> fix: handle error when creating public client in useHypercertClient hook

- allowlists/getAllowListRecordsForAddressByClaimed.tsx
- app/profile/[address]/page.tsx
- components/profile/account-switcher.tsx
- components/profile/contract-accounts-banner.tsx
- lib/isContract.ts
Without this patch, selecting any other account other than your connected EOA using the account selector doesn't do anything on your profile page. However, we want people to be able to cycle through their accounts, so whenever another account is selected via the account selector, we want the profile page to redirect to that account.
On the other hand we don't want the profile to automatically switch when the user is on a profile page that is not his connected EOA or one of the multisig they're a signer on. In these cases the selector will do nothing when the account selector is used.
ONLY MERGE AFTER #491!
> Switch profile page when another account selected

- components/hypercert/contributors.tsx
- components/hypercert/fractions.tsx
- components/user-name.tsx
- if user has hypercerts specific account, show username and avatar image 
- else if the address has ENS name, then show ENS name and avatar
- else show short/truncated address
- show percentages
> feat: display ENS/user name on contributor component
